### ISSUE TITLE
vanilla med tents and vehicles

### ISSUE THREAD

**Issue by topden** [diwako/armor_plates_system#101]
1. I understand that your system imposes its own damage and damage instead of vanilla, but then it turns out that you cannot use ARMA tents, containers and medical vehicles. This is a little sad, since only bandages remain to be treated (
I tested it on containers and tents. my life returns to 100%, but then it resets again to the damage that was before the treatment.
is it possible to somehow combine the restoration of life from vanilla cars, tents, etc.?
2. You can not change the plates lying down. The function does not work. Only standing or sitting. Is it possible to add the prone position as a permitted one? especially since you made the function to revive while lying down, it’s easier to change the plates than to revive a person)

**Comment by diwako** [comment]
> You can not change the plates lying down. The function does not work. Only standing or sitting. Is it possible to add the prone position as a permitted one? especially since you made the function to revive while lying down, it’s easier to change the plates than to revive a person)

This is by design as you add plates at the front of your vest, when being prone you are kind of blocking the way

The whole system was custom built to be accommodated to a certain play style that was requested, things like vanilla functions were not factored in and were not needed in that design.
