### ISSUE TITLE
Error message during revive

### ISSUE THREAD

**Issue by Corvorosso** [diwako/armor_plates_system#102]
**Mods (complete and add to the following information):**

- **Arma 3:**  2.10.149954 stable
  Community Base Addons v3.15.8
- **APS:**  0.8

  _Make sure to reproduce the issue with only CBA and Armor Plates on a newly created mission!_

**Description:**

17:59:22 Unknown attribute itemsCmd
17:59:22 Unknown attribute itemsCmd
17:59:28 Error in expression <or_plates_main_fnc_setUnconscious;

if (_consumeFAK) then {
    ["diw_armor_plat>
17:59:28   Error position: <_consumeFAK) then {
    ["diw_armor_plat>
17:59:28   Error Undefined variable in expression: _consumefak
17:59:28 File /z/diw_armor_plates/addons/main/functions/fnc_revive.sqf..., line 14
17:59:34 EPE manager release (0|16|0)
17:59:34 Number of joints in scene after release: 15
17:59:34 Number of actors in scene after release: 16
17:59:34 EPE manager release (0|16|0)
17:59:34 Number of joints in scene after release: 15
17:59:34 Number of actors in scene after release: 16
17:59:35 EPE manager release (0|16|0)
17:59:35 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
17:59:35 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
17:59:35 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
17:59:35 soldier[B_soldier_LAT_F]:Some of magazines weren't stored in soldier Vest or Uniform?
17:59:36 [CBA] (xeh) INFO: missionNamespace processed [false]
17:59:36 [CBA] (xeh) INFO: [10678,167.104,0] PreInit started. v3.15.8.220912
17:59:36 [CBA] (settings) INFO: Reading settings from settings file.
17:59:36 [CBA] (settings) INFO: Finished reading settings from settings file.
17:59:36 [CBA] (xeh) INFO: [10678,167.184,0] PreInit finished.
17:59:41 Shutdown normally

**Steps to reproduce:**

Form a squad, kill one of your team mates, wait until the medic treat the wounded

**Expected behavior:**

Error report and the Medic didn't consume the FAK

**Where did the issue occur?**

Singleplayer

**Additional context:**

no additional context

**Log Files:**

https://pastebin.com/JcU0w2gP

**Comment by diwako** [comment]
Thank you, it looks like this params needs a standard value for `_consumeFAK` then

https://github.com/diwako/armor_plates_system/blob/8d516f2ddea29a54c81795df4cf567ee93f65d60/addons/main/functions/fnc_revive.sqf#L2
