### ISSUE TITLE
Plate mass to setable variable

### ISSUE THREAD

**Issue by punch5545** [diwako/armor_plates_system#113]
Hi, I'm a addon staff of Korean ARMA 3 group.

We glad to use your this addon, and expecting to create more realistic battle experience.

but my users are sensitive to the weight of their equipments, so I tried decrease the weight of "Ceramic Plate" like:
```hpp
class CfgWeapons
{
    //armor plate system
	class ItemCore;
    class CBA_MiscItem;
    class CBA_MiscItem_ItemInfo;
    class diw_armor_plates_main_plate : CBA_MiscItem
    {
        class ItemInfo : CBA_MiscItem_ItemInfo
        {
            mass=22;
        };
    };
};
```

but it can decrease in Inventory, but cannot decrease after attach to plate carrier.

So I hope you add to CBA addon options about modify weight of plate. 

We using CBA, ACE3 mod.

Thank you for read this and appologize about my bad english.

**Comment by diwako** [comment]
Weight is hard set and cannot be changed. The configs are static, you will need to make a compat mod for such a thing

**Comment by punch5545** [comment]
> Weight is hard set and cannot be changed. The configs are static, you will need to make a compat mod for such a thing

Thanks for reply. I resolved override your script_components.hpp, fnc_addPlate, fnc_fillVestWithPlate and fnc_handleArmorDamage in my addon. 

I'll
