### ISSUE TITLE
Ai Teammates Downing and Reviving via Zeus (Module)

### ISSUE THREAD

**Issue by Xherdos** [diwako/armor_plates_system#12]
is there a way to add the Down&Revive system for the ai in zeus so i can get revived by my Teammates and that they can be downed too instead of dead?

Maybe something like a Module placed directly at them to enable it for those Ai Teammates you want that they don't die but get downed like a player and can revive too.

**Comment by diwako** [comment]
Would a solution that has Zeus Enhanced as dependency be alright?

**Comment by Xherdos** [comment]
For me it's alright i like to play with Zeus and if it Enchances the Mode it's good.
