### ISSUE TITLE
Downed marker enhancements

### ISSUE THREAD

**Issue by banzerschreck** [diwako/armor_plates_system#14]
**Is your enhancement related to a problem?**

While the 3d markers are great at pointing out where a downed ally is, they tend to cause people to bunch up to get the revive. An indication of if someone is currently reviving a downed ally would prevent this.
Additionally, the 3d marker provides little indication of how far away a downed ally is, which potentially wastes precious time during a firefight trying to figure out if its reasonable to attempt to revive them. A more concrete indication of distance may be helpful.
Support for turning these options on/off would be ideal since not all groups may want to use this additional information.

**Solution you'd like:**

Some form of indication if someone is currently reviving a downed ally.
A distance readout of how far away a downed ally is.
Options to enable/disable these features.

**Alternatives you've considered:**

To indicate someone is being revived, the marker could change to a different color, or be animated somehow e.g. growing/shrinking in size

**Additional context:**

https://imgur.com/a/tuthVM5
This screenshot is taken from my POV during Beagle's session on 6/25. It's obvious what direction the casualty is in but I have no idea how far away they are, making it a toss-up if I should try to get to them. They also may not even need me there since someone may be helping them already.

**Comment by diwako** [comment]
The indicators scale with distance and zoom. Default range is 100. Meaning if the indicator is rather small they are basically 80 - 90 meters away.  The downed player in the screenshot is around 30-40 meters away for example. I would not really want to add a distance number to them as well, as then they would be too precise.

For the icon changing when the patient being helped, I would not do a different color, another icon itself would be better. People can set their colors as they like and it should be not color dependent.
