### ISSUE TITLE
Invincibility after some time

### ISSUE THREAD

**Issue by xxthesilentwatcherxx** [diwako/armor_plates_system#17]
Mod's loaded: ACE, KAT MEDICAL RW (Airway and blood extensions (Modifies ACE to have blood types and airway functions)), Armor Plate System

Problem: After getting kitted up at an ACE arsenal I shoot the person wearing plates, they take damage. After about thirty minutes or so they become invincible against ALL types of damage including a nuke (which should set player and object health to 0 completely overriding ACE). 

Cause: Literally no idea. Originally thought it had something to do with the arsenal however after testing that theory I've concluded that the problem doesn't initiate from the arsenal itself.

**Comment by diwako** [comment]
You sure they were not set to disallow damage? If they were on your side, do you have the "disallow friendly fire" option enabled?

Besides that, I do not know if KAT medical might cause it or not.

**Comment by diwako** [comment]
Besides, would it be possible to upload an RPT, only try with ace medical and APS only? Maybe try to reproduce the issue. Right now it is hard to figure out why it is happening

**Comment by Gelox1209** [comment]
Can confirm I'm been only using ace medical and armor plates system and the invulnerability bug does happen, though I'm unsure of the cause. It just seems like it happens after some time, I've tried a lot of things involving replacing the plates and messing with it via arsenal, but that doesn't seem like the issue.

**Comment by diwako** [comment]
Have either of you changed the plate HP during the session? That is playing without restarting the mission?

**Comment by Gelox1209** [comment]
I've made a lot of changes to the base settings, the changes were made during a previous mission, and then I stopped the server entirely and then started the server whenever running the same configs and mission.

**Comment by diwako** [comment]
So to reiterate. you have restarted the mission (or server, both have the same effect in this case) after changing settings. then you play as normal. out of a sudden you do not take any damage what so ever on any body part?

**Comment by Gelox1209** [comment]
Yes, and this invincibility bug only happens after sometime, it can be fixed temporarily if you leave and rejoin, but eventually you'll be invincible again.

**Comment by diwako** [comment]
Could you provide me an RPT file from a session when this happened? With it i can see what kind of other mods are loaded and if there are maybe some errors thrown.

**Comment by diwako** [comment]
Another question, did you die and respawn during the mission?

**Comment by Gelox1209** [comment]
I was able to die and respawn, but if I survive for a prolonged time eventually it'll make me invincible.
Here's the rpt, it is home hosted on one of my machines and the mission is the well known anti stasi., I apologize for the super long file as I usually keep it on for a long time.

(Changed file extension to log cause github wouldn't let me upload)
[arma3server log.log](https://github.com/diwako/armor_plates_system/files/6734268/arma3server.log.log)

**Comment by diwako** [comment]
Oh, sorry, meant the rpt from a client machine, so a player.

**Comment by diwako** [comment]
I looked through both RPTs, There is no error in it from APS. So it has to be a runtime issue. This means gotta figure out what the actually trigger of the issue is.

Any specifics you remember when it happens? Reproducing the issue is now key.

**Comment by Gelox1209** [comment]
When invincible, there was no damage indicator since that was enabled, and no blood splatter. Ive tried reproducing it as I noticed the arsenal does get rid of the plate hp so I thought it mightve had to do something with that, but no luck so far. Ill keep you updated if I find anything, and let me know if you want me to try something.

**Comment by diwako** [comment]
The arsenal does replace your vest with another. While it does not look like it on your end, it is actually a different container. The plates are attached to the container and if that one is replaced, so will the plates.

However you telling me that the damage indicators stopped is a good hint. Which makes me wonder if the damage event handler has been removed for some reason.

**Comment by Gelox1209** [comment]
I played by myself on the dedicated for two days and I haven't gotten the bug anymore, which is really weird.

**Comment by Gelox1209** [comment]
Two things happened that allowed the bug to happen but I dont know which or why.
I logged in to use zeus, and someone else joined the server.

**Comment by diwako** [comment]
I have released a new version. It might fixes this issue, please keep me up to date.
