### ISSUE TITLE
Toggle for more arcade-like mode with ACE medical

### ISSUE THREAD

**Issue by Alice196498** [diwako/armor_plates_system#22]
I found that the original way the plates worked in verſion 2.0 with ACE medical ſtruck a good balance between a more arcade-ſtyle mechanick and realiſm with the plates acting ſimilarly to health that could be repleniſhed by replacing damaged plates, and the ACE medical features coming into play when the player can no longer replace them or has no time to do ſo. It is for this reaſon that I propoſe the following ſolution :—

A toggle button in the options to uſe the current, more realiſtick functionality, or the more arcade-ſtyle previous functionality.

Alternatively, perhaps having more options to control the functionality itſelf would be more uſer-friendly in that the uſer could then cuſtomize the level of realiſm to their own ſtyle and preference or the need of the miſſion ; as, whether the plates protect the entire body, the body aſide from the head, or juſt the torſo ; the thickneſs and whether it affect the plates or not ; whether the plates are deſtroyed faſter with the integrity or not, as well as the ſpeed or efficacy of this.

**Comment by diwako** [comment]
Okay not to be rude, the use of the old style S jumbled my brain a little on a monday morning, so it was a bit hard to read.

A roll back will not happen as damage logic between standalone and ace medical has been separated. I can take a look in adding more options. The whole body protection option is however a bit harder to implement. So do not expect this feature to be added for next version for now.

**Comment by Alice196498** [comment]
All right, thank you. It’s intereſting that the ſyſtems have been ſeparated—I think that’s a good move. You’re not rude at all ; I appreciate your help, and I don’t try to make things more difficult : this is juſt how I type.

I don’t expect anything to be implemented, as I realize that it’s a lot of work and very difficult. Thank you for conſidering my ſuggeſtion ; even if it takes time, I’d be glad to ſee what you do with it, becauſe the mod is already amazing and very well done.
