### ISSUE TITLE
In-session respawn support

### ISSUE THREAD

**Issue by nullAurelian** [diwako/armor_plates_system#33]
**Current Behavior:**
During the bleeding out timer player view slowly darkens and shows a skull image. This effect persists after player uses the vanilla respawn settings for missions with respawn enabled. 

**Expected Behavior:**
After a player respawns in session the bleeding out effect should be removed and reset from player.

**Why not rejoin in progress:**
Overly punishing for players when mission is designed for long play, ie a co-op 'campaign' to retake an island.

**Why do you need this**
To create a mission that supports player respawn without having to exit and JIP repeatedly.

**Comment by nullAurelian** [comment]
To replicate:
1. Load in a multiplayer mission with respawns enabled. 
2. Force a respawn. Should be able to be done by pressing escape to manually respawn or forcing a revive state by self-damage. If necessary use the give up function.
3. Respawn at location 
4. Wait for skull to appear. Player vision should be blurry during the wait period.

Is it possible to change label to Bug then?

**Comment by diwako** [comment]
Thanks for the report. Weird. sounds like the "killed" event is not firing as it should remove the skull overlay.

**Comment by diwako** [comment]
Just tried it out. Cannot reproduce. Forcing a respawn via escape menu or via Give up action both gets rid of the skull.

Can you find out what the respawn delay on those missions are? Usually those are set in `description.ext` with attribute `respawnDelay`.

Which units did you use as players? That is which are placed down via the editor.

Additionally is it possible to get an RPT log file?

Right now my suspicion is, that something is breaking the "Killed" event handler and thus nothing gets reset properly.

**Comment by diwako** [comment]
Additionally if you have the mission maker check. make them right click on a player unit in 3den, open config viewer.

The Config viewer opens then with the unit class selected. Double click "Eventhandlers", then get confused why the config viewer breaks and jumps somewhere completely different, find the unit config again buy scrolling up or down. Then make a screenshot of the event handler entry.

It should look similar to this

![image](https://user-images.githubusercontent.com/8259498/124434753-8ad39900-dd74-11eb-8174-a23e9cf0c125.png)

**Comment by diwako** [comment]
Closing because of old issue
If the issue persists feel free to reopen
