### ISSUE TITLE
Healing self does not consume a FAK

### ISSUE THREAD

**Issue by diwako** [diwako/armor_plates_system#39]
**Mods (complete and add to the following information):**

- **APS:** `0.4.2`

**Description:**

when self healing when HP bar is orange as none medic does not consume a FAK.

**Expected behavior:**

Eats the FAK, heals me

**Where did the issue occur?**

- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Comment by fariparedes** [comment]
Fixed by #46
