### ISSUE TITLE
Players don't respawn with plates

### ISSUE THREAD

**Issue by MrFleff** [diwako/armor_plates_system#41]
**Mods:**
- **CBA:** `3.15.5`
- **APS:** `0.4.2`
- **ACE:** [`0.13.6`](
[Arma3_x64_2021-07-13_19-35-54.zip](https://github.com/diwako/armor_plates_system/files/6812700/Arma3_x64_2021-07-13_19-35-54.zip)
)

**Description:**
With "Players spawn with full plates" checked, players will have plates on initial spawn; however, on respawn players do not have plates. 

**Steps to reproduce:**
- Spawn a single unit, a respawn module, and enable respawns.
- Ensure "Players spawn with full plates" is checked
- Run mission in multiplayer setting

**Expected behavior:**
Expected players to respawn with full plates on themselves.

**Where did the issue occur?**
Dedicated & Self-Hosted Multiplayer

**Additional context:**
Tested with and without ACE Medical, this had no change on the problem.
CBA was recently updated, unsure if this would have been a cause.

**Log Files:**
[Arma3_x64_2021-07-13_19-35-54.zip](https://github.com/diwako/armor_plates_system/files/6812715/Arma3_x64_2021-07-13_19-35-54.zip)

**Comment by diwako** [comment]
The feature was intended for only the original spawn in, after loading in from slotting screen, not on a respawn. Would you like to see this behavior changed so it also adds plates on a respawn?

**Comment by MrFleff** [comment]
Hm, maybe I misunderstood it then. Though I recall it mentioning respawn when you hover your mouse over the option that describes the action.
With that said, an option to have plates added to player respawning would be great.

**Comment by diwako** [comment]
You are right, it mentions respawning. Seems like I either slacked off or had a change of heart in the middle of it and forgot to change the text. Either way this should be added so it fits to the description.
