### ISSUE TITLE
PvP - Damage while downed

### ISSUE THREAD

**Issue by Desertcyclone** [diwako/armor_plates_system#43]
Mainly for PvP - Option to allow/disallow "thirsting", where players can be killed in a downed state or where hits in the downed state reduce the amount of time remaining to revive.

**Comment by Beaglerush** [comment]
Second this but asking for it as a PvE option too. Would be nice to be able to be finished off in the downed state by both players and the AI. Having AI target the downed player, requiring teammates to work harder to cover and retrieve the casualty. Ideally AI prefers to shoot non-downed teammates first if they're similarly easy targets?
