### ISSUE TITLE
Radio disable while downed

### ISSUE THREAD

**Issue by Desertcyclone** [diwako/armor_plates_system#44]
Option to disable a person's radio while they are downed, primarily for PvP.

**Comment by diwako** [comment]
Looked into that.

for tfar can be done like so
`_unit setVariable ["tf_unable_to_use_radio", true, true];`

for ACRE. not possible without muting the unit in the process
`_unit setVariable ["acre_sys_core_isDisabled", true, true];`

might needs a function to cut off ongoing transmissions, like so
https://github.com/acemod/ACE3/blob/master/addons/common/functions/fnc_endRadioTransmission.sqf

**Comment by Desertcyclone** [comment]
This should now be possible with ACRE using the new radio block options in ACRE's update - https://github.com/IDI-Systems/acre2/pull/1159

Option could be two checkboxes, "Disable radio when downed" and "Disable push to talk when downed". Alternatively the option could be a drop down selector of "Communications available while downed" and the options could be "Full communications", "No radio usage", and "No radio or push to talk".
