### ISSUE TITLE
Player self-revive

### ISSUE THREAD

**Issue by genjonakasone** [diwako/armor_plates_system#5]
**Is your enhancement related to a problem?**

As AI is currently incapable of reviving a downed player, a feature of "second chance" or "second breath" for player would be a nice addition.

**Solution you'd like:**

Create an option in addon settings to let players self-revive:
- choose how many times can they do this
- choose how much HP do they heal depending on skill
- maybe a % chance of fully healing?
- how long does it take
- decide whether AI will shoot downed player or not and a time margin after which player's back on his feet?

**Alternatives you've considered:**

Maybe make the mod able to coexist with Project Injury Reaction?

**Additional context:**

None

**Comment by diwako** [comment]
Personally I wanna keep the standalone medical mode simple. Meaning I would rather see the revive timer/bar being longer than having a chance for it to fail. Healing should also be predictable, like a % of max health every time.

about Project Injury Reaction. Never played with it, so no idea really.

**Comment by genjonakasone** [comment]
Yeah, I understand your point. So how about just giving a self-interaction with already-written functions to heal yourself if used in Single Player or without any other players?

**Comment by diwako** [comment]
Personally thinking on doing just that. Add a new cba setting to make the action available, as time i would just use the revive timer multiplied by two that is available for that unit anyways, same for healing %.

**Comment by diwako** [comment]
PR created.

It is a CBA setting that is off by default. It takes double the amount of time you'd need to revive someone else, you will need to have a fak or a med kit on your. (med kit only works if you are a a medic)

**Comment by genjonakasone** [comment]
Awesome, thank you
