### ISSUE TITLE
Editor Modules

### ISSUE THREAD

**Issue by hunterczech** [diwako/armor_plates_system#63]
**Is your enhancement related to a problem?**

Modules that could MIssion Maker place and attach them to individuals to give them specific settings like HP / HP Regen or maybe even Armor plate strength. This way can missions are guaranteed to be equal regardless of chosen settings. These modules would of course overwrite settings if the individual had configured module attached to them.

**Solution you'd like:**

1 or more Modules that gives mission maker options to define various addon's settings per individual soldiers.

**Alternatives you've considered:**

Script commands instead of modules

**Additional context:**

Let's say I want to have variable durability for each AI soldier - I want one soldier with 150 HP, second one with 300 HP. Even in real life each human can have different durabilities. I want to configure them individually.

**Comment by diwako** [comment]
Per unit max HP is already a thing. it is not a module, it is an attribute directly on the unit itself. Double click the unit, scroll down to find the armor plate options. There is a slider that will set the units max HP. 

For HP regen, no there is no such setting so far.

**Comment by hunterczech** [comment]
Thanks! I never noticed before. I really like this but what kinda sucks is that when you open arsenal the amount of plates you had before disappears completely. Is there any way to avoid this?

**Comment by diwako** [comment]
No, when you open and close the arsenal, your vest will be removed and readded. the plates are in the vests container object, which will be replaced then.

**Comment by hunterczech** [comment]
Allright I'm closing the issue then.
